version: '3.8'
services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    volumes:
      - "~/db_postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=recruitment_dev
    networks:
      - db
  recruitment_backend2023:
    build: .
    container_name: recruitment_backend_2023
    ports:
      - "3333:3333"
    volumes:
      - "./data/logs:/app/data/logs"  #日志
      - "./data/resumes:/app/data/resumes" #简历
    networks:
      - db
    depends_on:
      - db_postgres
networks:
  db:
    external: true
    name: db
