version: '3.8'
services:
  recruitment_backend_2023:
    build: .
    container_name: recruitment_backend_2023
    ports:
      - "3333:3333"
    volumes:
      - "./data/logs:/app/data/logs"  #日志
      - "./data/resumes:/app/data/resumes" #简历
    networks:
      - db
networks:
  db:
    external: true
    name: db
